version: '3'
services:
  api:
    image: metadata-service_api
    container_name: api
    ports:
      - 8080:8080
    links:
      - mongo:mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017